name: Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Display Java, Gradle, and Android SDK versions
        run: |
          java -version
          javac -version
          echo "JAVA_HOME=$JAVA_HOME"
          ./gradlew --version
          echo "ANDROID_HOME=$ANDROID_HOME"
          ls -la $ANDROID_HOME/platforms

      - name: Check for compilation errors
        run: ./gradlew compileDebugKotlin --stacktrace

      - name: Build with Gradle
        run: ./gradlew assembleDebug --info

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
